function [R,t,s] = similarity_registration(x,y)
xbar = mean(x,2);
ybar = mean(y,2);
xt = x- xbar;
yt = y- ybar;
H = (yt)*(xt)';
[U, ~, V] = svd(H); 
R = U*diag([1,det(U*V')])*V';
% s = sum(yt'*R*xt)/sum(vecnorm(xt).^2);
s = sum(diag(yt'*R*xt))/sum(vecnorm(xt).^2);
t = ybar - s*R*xbar;
